### ISSUE TITLE
Can't build today - heap exhausted on sbcl

### ISSUE THREAD

**Issue by quicklisp** [guicho271828/trivialib.type-unify#4]
I can't build the project because of heap exhaustion. Do you get that as well on the latest SBCL?

**Comment by guicho271828** [comment]
This is because of the change in the pattern match optimizer algorithm.
The new one emits a faster but larger code. I already have a limit on the code size, but this seems a bit too large. I reduced the limit from 500 to 300 and it builds fine on SBCL 1.5.1 with 1GB heap. https://github.com/guicho271828/trivia/commit/9783d3a0b6e6be7a274a7d47f7baf55a2f3733bd

**Comment by guicho271828** [comment]
verified on CCL.
